---
Description: Automate provisioning of CodePipeline, CodeCommit, CodeBuild, CloudWatch Events and
  CodeDeploy. **WARNING** This template creates one or more Amazon EC2 instances.
  You will be billed for the AWS resources used if you create a stack from this template.
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  RepositoryName:
    Description: The name for the CodeCommit repo
    Type: String
  EmailAddress:
    Description: Email Address for sending SNS notifications for CodeCommit
    Type: String
  RepositoryBranch:
    Description: The name of the branch for the CodeCommit repo
    Type: String
    Default: master
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Can contain only ASCII characters.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Dynamic Configuration
      Parameters:
      - RepositoryBranch
    ParameterLabels:
      RepositoryName:
        default: CodeCommit Repository Name
      RepositoryBranch:
        default: CodeCommit Repository Branch
Resources:
  EventRule: 
    Type: "AWS::Events::Rule"
    Properties: 
      Description: "EventRule"
      EventPattern: 
        source:
        - aws.codepipeline
        detail-type:
        - CodePipeline Pipeline Execution State Change
        detail:
          state:
          - FAILED
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Ref: "MySNSTopic"
          Id: "PipelineNotificationTopic"
          InputTransformer:
            InputTemplate: '"The Pipeline <pipeline> has failed. Go to https://console.aws.amazon.com/codepipeline/home?region=us-east-1#/view/<pipeline>" '
            InputPathsMap:
              pipeline: "$.detail.pipeline" 
  
  CodeBuildTemplates:
    Type: AWS::CodeBuild::Project
    Properties:
      Name:
        Ref: AWS::StackName
      Description: Build application
      ServiceRole: !ImportValue rde:roles:api:buildrole
      Artifacts:
        Type: no_artifacts
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:10.1.0
      Source:
        Location:
          Fn::Join:
          - ''
          - - https://git-codecommit.
            - Ref: AWS::Region
            - ".amazonaws.com/v1/repos/"
            - Ref: AWS::StackName
        Type: CODECOMMIT
      TimeoutInMinutes: 10
      Tags:
      - Key: Owner
        Value: Ref:AWS::StackName - CodeBuild
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint:
          Ref: EmailAddress
        Protocol: email
  # CodeCommitRepo:
  #   Type: AWS::CodeCommit::Repository
  #   Properties:
  #     RepositoryName:
  #       Ref: AWS::StackName
  #     RepositoryDescription: CodeCommit Repository for RDE-APP Solution
  #     Triggers:
  #     - Name: MasterTrigger
  #       CustomData:
  #         Ref: AWS::StackName
  #       DestinationArn:
  #         Ref: MySNSTopic
  #       Events:
  #       - all
  CodePipelineStack:
    Type: AWS::CodePipeline::Pipeline
    DependsOn: CodeBuildTemplates
    Properties:
      Name: !Ref AWS::StackName
      RoleArn: !ImportValue rde:roles:api:pipelinerole
      Stages:
      - Name: Source
        Actions:
        - InputArtifacts: []
          Name: Source
          ActionTypeId:
            Category: Source
            Owner: AWS
            Version: '1'
            Provider: CodeCommit
          OutputArtifacts:
          - Name: MyApp
          Configuration:
            BranchName:
              Ref: RepositoryBranch
            RepositoryName:
              !Ref RepositoryName
          RunOrder: 1
      - Name: Build
        Actions:
        - InputArtifacts:
          - Name: MyApp
          Name: Build
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: '1'
            Provider: CodeBuild
          OutputArtifacts:
          - Name: MyAppBuild
          Configuration:
            ProjectName:
              Ref: CodeBuildTemplates
          RunOrder: 1
      ArtifactStore:
        Type: S3
        Location: !ImportValue rde:template:resources:artifactbucket
Outputs:
  PipelineUrl:
    Value:
      Fn::Join:
      - ''
      - - https://console.aws.amazon.com/codepipeline/home?region=
        - Ref: AWS::Region
        - "#/view/"
        - Ref: CodePipelineStack
    Description: CodePipeline URL

  GitCloneCommand:
    Value:
      Fn::Join:
      - ''
      - - "git clone https://git-codecommit."
        - Ref: AWS::Region
        - ".amazonaws.com/v1/repos/"
        - !Ref RepositoryName
        - "/"
    Description: Git Repository URL
